# Site settings
title: Random thoughts and views
email: admin@yashsriv.org
description: >
  Blog of Yash Srivastav. An enthusiastic developer and open source contibutor.
baseurl: ""
url: "https://yashsriv.org"
author: "Yash Srivastav"
twitter_username: therealyashsriv
github_username: yashsriv
facebook_username: yash98
google_username: YashSrivastav98

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      []
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
keep_files:
  - .git
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
  - emoji_for_jekyll
  - liquid_pluralize
  - jekyll-last-modified-at
  - jekyll-mentions
  - jekyll-gist
  - liquid_reading_time
  - jekyll-sitemap

# Conversion
markdown:          kramdown
highlighter:       rouge
lsi:               false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    8000
host:    127.0.0.1

# Outputting
permalink: /:year/:month/:title.html
paginate_path: /page:num
timezone: null

quiet: false
verbose: false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

emoji-additional-keys: ["title"] 
